version: "3.8"

services:
  server:
    container_name: nodejs-server
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      mongo:
        condition: service_started
    networks:
      - server-network

  mongo:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"
    networks:
      - server-network

volumes:
  mongo_data:
  mongo_config:

networks:
  server-network:
    driver: bridge
